-- MySQL Script generated by MySQL Workbench
-- 01/26/15 09:25:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `idUtilisateur` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomUtilisateur` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUtilisateur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Facture` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Facture` (
  `idFacture` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Facturecol` VARCHAR(45) NULL,
  `date` DATE NULL,
  `prixHT` FLOAT NOT NULL,
  `prixTotal` FLOAT NOT NULL,
  `taxe` FLOAT NOT NULL,
  `Utilisateur_idUtilisateur` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFacture`),
  UNIQUE INDEX `idFacture_UNIQUE` (`idFacture` ASC),
  INDEX `fk_Facture_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Facture_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SousCategorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SousCategorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SousCategorie` (
  `idCategorie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorie`),
  UNIQUE INDEX `idCategorie_UNIQUE` (`idCategorie` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Objet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Objet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Objet` (
  `idObjet` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `stock` INT NOT NULL,
  `prix` FLOAT NOT NULL,
  `promotions` VARCHAR(45) NULL,
  `SousCategorie_idCategorie` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idObjet`),
  UNIQUE INDEX `idObjet_UNIQUE` (`idObjet` ASC),
  INDEX `fk_Objet_SousCategorie1_idx` (`SousCategorie_idCategorie` ASC),
  CONSTRAINT `fk_Objet_SousCategorie1`
    FOREIGN KEY (`SousCategorie_idCategorie`)
    REFERENCES `mydb`.`SousCategorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Adresse` (
  `idadresse` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomRue` VARCHAR(45) NULL,
  `codePostal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `nomDestinaire` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  `Utilisateur_idUtilisateur` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idadresse`),
  UNIQUE INDEX `idadress_UNIQUE` (`idadresse` ASC),
  INDEX `fk_Adresse_Utilisateur_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Adresse_Utilisateur`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `idCategorie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `SousCategorie_idCategorie` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCategorie`),
  UNIQUE INDEX `idCategorie_UNIQUE` (`idCategorie` ASC),
  INDEX `fk_Categorie_SousCategorie1_idx` (`SousCategorie_idCategorie` ASC),
  CONSTRAINT `fk_Categorie_SousCategorie1`
    FOREIGN KEY (`SousCategorie_idCategorie`)
    REFERENCES `mydb`.`SousCategorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Objet_has_Facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Objet_has_Facture` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Objet_has_Facture` (
  `Objet_idObjet` INT UNSIGNED NOT NULL,
  `Facture_idFacture` INT UNSIGNED NOT NULL,
  `commentaire` VARCHAR(45) NULL,
  `note` INT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`Objet_idObjet`, `Facture_idFacture`),
  INDEX `fk_Objet_has_Facture_Facture1_idx` (`Facture_idFacture` ASC),
  INDEX `fk_Objet_has_Facture_Objet1_idx` (`Objet_idObjet` ASC),
  CONSTRAINT `fk_Objet_has_Facture_Objet1`
    FOREIGN KEY (`Objet_idObjet`)
    REFERENCES `mydb`.`Objet` (`idObjet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Objet_has_Facture_Facture1`
    FOREIGN KEY (`Facture_idFacture`)
    REFERENCES `mydb`.`Facture` (`idFacture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
