package markingmenu;

import markingmenu.listener.MarkingMenuItemExtendListener;
import markingmenu.listener.MarkingMenuItemListener;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import javax.swing.Timer;
import markingmenu.popup.TranslucentPopupFactory;

/**
 * @author Nathan
 * @author Jean-Luc
 */
public class MarkingMenu extends javax.swing.JPanel implements MarkingMenuItemExtendListener {

    private JFrame myFrame;
    private MarkingMenuState state;
    private Popup popup;
    private int nbOptions;
    private Timer timer;
    private List<MarkingMenuItem> items;
    private List<String> labelOptions;
    private MarkingMenuItemListener observers;
    private final static int MARKING_MENU_RAYON = 100;
    private final static int DELAT_ERROR = 30;
    private Point originPoint, draggedPoint,lastDraggedPoint;
    private boolean eraseRubberBanding = false;

    /**
     * Creates new form Pie
     */
    public MarkingMenu() {
        this(Arrays.asList("one", "two", "three", "four", "five", "six", "seven"));
    }

    public MarkingMenu(List<String> label) {
        initComponents();
        items = new ArrayList();
        observers = null;
        
        timer = new Timer(1000, (ActionEvent e) -> {
            timerListner();
        });

        initMarkingMenu(label);
        initFactory(0, 0);
        initState();
    }

    /**
     * *****************************************************************************
     *** INITIALIZATION METHODS
     * ******************************************************************************
     */
    public final void initMarkingMenu(List<String> labels) {
        if (!isSameOptions(labels)) {
            labelOptions = labels;
            nbOptions = getLabelOptions().size();
            MarkingMenuItem app;

            for (MarkingMenuItem item : items) {
                remove(item);
            }
            items.clear();

            for (int i = 1; i <= nbOptions; i++) {
                Color c = getRandomColor();
                app = new MarkingMenuItem(c, i, nbOptions, labelOptions.get(i - 1), this);
                items.add(app);
                add(app);
                app.repaint();
            }
        }

    }

    private void initFactory(int posX, int posY) {
        PopupFactory factory /*= TranslucentPopupFactory.getSharedInstance()*/;
        PopupFactory.setSharedInstance(new TranslucentPopupFactory());
        factory = PopupFactory.getSharedInstance();
        int x = posX - (getPreferredSize().width / 2);
        int y = posY - (getPreferredSize().height / 2);

        hide();
        popup = factory.getPopup(myFrame, this, x, y);
    }

    public void initState() {
        state = MarkingMenuState.IDLE;
        removeMarkingMenuItemClick();
        hide();
    }

    public void show() {
        if (popup != null) {
            popup.show();
        }
    }

    public void hide() {
        if (popup != null) {
            popup.hide();
        }
    }

    /**
     * *****************************************************************************
     *** ADD / REMOVE OBSERVERS METHODS
     * ******************************************************************************
     */
    public void addMarkingMenuItemClick(MarkingMenuItemListener itemClickListener) {
        observers = itemClickListener;
    }

    public void removeMarkingMenuItemClick() {
        observers = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        setLayout(new javax.swing.OverlayLayout(this));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    /**
     * *****************************************************************************
     *** LISTENER METHODS
     * ******************************************************************************
     */
    private void timerListner() {
        switch (state) {
            case MENU:
                state = MarkingMenuState.MENU;
                //highlight()
                break;
            case IDLE:
                //INTERDIT
                break;
            case MARKING:
                state = MarkingMenuState.VISIBLE;
                timer.stop();
                show();
                break;
            case VISIBLE:
                state = MarkingMenuState.VISIBLE;
                show();
                //do nothing
                break;
            case INVISIBLE:
                state = MarkingMenuState.INVISIBLE;
                hide();
                //do nothing
                break;
        }

    }

    public void mouseMarkingMenuPressed(MouseEvent e) {
        switch (state) {
            case MENU:
                if (e.getButton() == MouseEvent.BUTTON1) {
                    state = MarkingMenuState.IDLE;
                    hide();
                } else if (e.getButton() == MouseEvent.BUTTON3) {
                    state = MarkingMenuState.MARKING;
                    originPoint = new Point(e.getXOnScreen(), e.getYOnScreen());
                    timer.start();
                }

                break;
            case IDLE:
                state = MarkingMenuState.MARKING;
                originPoint = new Point(e.getXOnScreen(), e.getYOnScreen());
                timer.start();
                break;
            case MARKING:
                //INTERDIT
                break;
            case VISIBLE:
                //INTERDIT
                break;
            case INVISIBLE:
                //INTERDIT
                break;
        }
    }

    public void mouseMarkingMenuReleased(MouseEvent e, int nbOptions) {
        timer.stop();
        switch (state) {
            case MENU:
                //INTERDIT
                break;
            case IDLE:
                //INTERDIT
                break;
            case MARKING:
                state = MarkingMenuState.MENU;
                show();
                break;
            case VISIBLE:
                if (isInItemMenu() != -1) {
                    state = MarkingMenuState.IDLE;
                    fireObserversForItemAction(isInItemMenu());
                    hide();
                } else {
                    state = MarkingMenuState.IDLE;
                    hide();
                }
                break;
            case INVISIBLE:
                if (computeIsInInvisibleMenu(nbOptions) != -1) {
                    state = MarkingMenuState.IDLE;
                    fireObserversForItemAction(computeIsInInvisibleMenu(nbOptions));
                    hide();
                } else {
                    state = MarkingMenuState.IDLE;
                    hide();
                }
                lastDraggedPoint = null;
                setEraseRubberBanding(true);
                break;
        }
    }

    public void mouseMarkingMenuDragged(MouseEvent e) {
        switch (state) {
            case MENU:
                //INTERDIT
                break;
            case IDLE:
                //INTERDIT
                break;
            case MARKING:
                state = MarkingMenuState.INVISIBLE;
                timer.stop();
                break;
            case VISIBLE:
                //INTERDIT
                break;
            case INVISIBLE:
                setLastDraggedPoint(getDraggedPoint());
                setDraggedPoint(new Point(e.getXOnScreen(), e.getYOnScreen()));
                state = MarkingMenuState.INVISIBLE;
                //do nothing
                break;
        }
    }

    private void fireObserversForItemAction(int position) {
        if (observers != null) {
            observers.actionMarkingMenuPerformed(position);
            items.get(position - 1).setHighLight(false);
            removeMarkingMenuItemClick();
        }
        for (MarkingMenuItem item : items) {
            item.setHighLight(false);
        }
    }

    /**
     * *****************************************************************************
     *** OVERRIDE LISTENER METHODS
     * ******************************************************************************
     */
    @Override
    public void actionMarkingMenuItemClicked(int position, MouseEvent e) {
        if (e.getButton() == MouseEvent.BUTTON1) {
            switch (state) {
                case MENU:
                    if (isInItemMenu() != -1) {
                        state = MarkingMenuState.IDLE;
                        //commande
                        fireObserversForItemAction(position);
                        hide();
                    } else {
                        state = MarkingMenuState.IDLE;
                        hide();
                    }
                    break;
                case IDLE:
                    //INTERDIT
                    break;
                case MARKING:
                    //INTERDIT
                    break;
                case VISIBLE:
                    //INTERDIT
                    break;
                case INVISIBLE:
                    //INTERDIT
                    break;
            }
        }
    }

    @Override
    public void actionMarkingMenuItemEntered(int position, MouseEvent e) {
        items.get(position - 1).setMouseIn(true);
        items.get(position - 1).setHighLight(true);
    }

    @Override
    public void actionMarkingMenuItemExited(int position, MouseEvent e) {
        items.get(position - 1).setMouseIn(true);
        items.get(position - 1).setHighLight(false);
    }

    /**
     * *****************************************************************************
     *** COMPUTATION METHODS
     * ******************************************************************************
     */
    private int isInItemMenu() {
        int pos = -1;
        for (int i = 0; i < items.size(); i++) {
            if (items.get(i).isMouseIn()) {
                return i + 1;
            }
        }
        return pos;
    }

    private boolean isSameOptions(List<String> labels) {
        if (labels.size() == items.size()) {
            for (int i = 0; i < items.size(); i++) {
                if (!labels.get(i).equals(items.get(i).toString())) {
                    return false;
                }
            }
            return true;
        }
        return false;
    }

    private int computeIsInInvisibleMenu( int nbOptions) {
        int distance = (int) draggedPoint.distance(originPoint);
        Point originRepere = new Point(originPoint.x, originPoint.y - MARKING_MENU_RAYON);
        double angleSection = 360 / nbOptions;
        double angle = angleBetweenTwoPointsWithFixedPoint(draggedPoint.getX(), draggedPoint.getY(), originRepere.x, originRepere.y, originPoint.x, originPoint.y);
        angle = Math.toDegrees(angle);

        if (distance < MARKING_MENU_RAYON && distance > DELAT_ERROR) {
            if (angle < 0) {
                angle += 360;
            }
            return (int) ((angle / angleSection) + 1);
        } else {
            return -1;
        }
    }

    private static double angleBetweenTwoPointsWithFixedPoint(double point1X, double point1Y,
            double point2X, double point2Y,
            double fixedX, double fixedY) {

        double angle1 = Math.atan2(point1Y - fixedY, point1X - fixedX);
        double angle2 = Math.atan2(point2Y - fixedY, point2X - fixedX);

        return angle1 - angle2;
    }

    private Color getRandomColor() {
        Random r = new Random();
        int rouge = r.nextInt(128);
        int vert = r.nextInt(128);
        int bleu = r.nextInt(128);

        return new Color(rouge + 128, vert + 128, bleu + 128);
    }

    /**
     * *****************************************************************************
     *** GETTER / SETTER METHODS
     * ******************************************************************************
     */
    public MarkingMenuState getState() {
        return state;
    }

    public String getLabel(int numOption) {
        return labelOptions.get(numOption);
    }

    public List<String> getLabelOptions() {
        return labelOptions;
    }

    public void setListActions(List<String> label, int posX, int posY) {
        initMarkingMenu(label);
        initFactory(posX, posY);
    }

    public List<MarkingMenuItem> getItems() {
        return items;
    }
    
    /**
     * @return the originPoint
     */
    public Point getOriginPoint() {
        return originPoint;
    }

    /**
     * @param originPoint the originPoint to set
     */
    public void setOriginPoint(Point originPoint) {
        this.originPoint = originPoint;
    }

    /**
     * @return the draggedPoint
     */
    public Point getDraggedPoint() {
        return draggedPoint;
    }

    /**
     * @param draggedPoint the draggedPoint to set
     */
    public void setDraggedPoint(Point draggedPoint) {
        this.draggedPoint = draggedPoint;
    }

    /**
     * @return the lastDraggedPoint
     */
    public Point getLastDraggedPoint() {
        return lastDraggedPoint;
    }

    /**
     * @param lastDraggedPoint the lastDraggedPoint to set
     */
    public void setLastDraggedPoint(Point lastDraggedPoint) {
        this.lastDraggedPoint = lastDraggedPoint;
    }

    /**
     * @return the eraseRubberBanding
     */
    public boolean isEraseRubberBanding() {
        return eraseRubberBanding;
    }

    /**
     * @param eraseRubberBanding the eraseRubberBanding to set
     */
    public void setEraseRubberBanding(boolean eraseRubberBanding) {
        this.eraseRubberBanding = eraseRubberBanding;
    }

}
