/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package markingmenu;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

/**
 *
 * @author hakje
 */
public class MarkingMenu extends javax.swing.JPanel {

    private int nbOptions;
    private List<MarkingMenuItem> options;
    private List<String> labelOptions;
    
    /**
     * Creates new form Pie
     */
    public MarkingMenu() {
        this(Arrays.asList("one", "two", "three", "four", "five", "four", "five"));
    }

    public MarkingMenu(List<String> label) {
        initComponents();
        options = new ArrayList();
        initMarkingMenu(label);
    }
    
    public final void initMarkingMenu (List<String> label) {
        labelOptions = label;
        nbOptions = labelOptions.size();
        MarkingMenuItem app;
        
        for (int i = 1; i <= nbOptions; i++) {
            Color c = getRandomColor();
            app = new MarkingMenuItem(c, i, nbOptions,""+i);
            options.add(app);
            add(app);
        }
    }
    
    public void setMarkingMenu (List<String> label) {
        initMarkingMenu(label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        setLayout(new javax.swing.OverlayLayout(this));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private Color getRandomColor() {
        Random r = new Random();
        int rouge = r.nextInt(126);
        int vert = r.nextInt(126);
        int bleu = r.nextInt(126);

        return new Color(rouge+126, vert+126, bleu+126);
    }
}
