/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package markingmenu;

import autresProjets.ArcProgressPane;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Random;

/**
 *
 * @author hakje
 */
public class Pie extends javax.swing.JPanel {

    private int nbOptions;

    /**
     * Creates new form Pie
     */
    public Pie() {
        this(4);
    }

    public Pie(int nbO) {
        initComponents();
        nbOptions = nbO;
        ArcProgressPane app;
        Random r = new Random();

        for (int i = 1; i <= nbOptions; i++) {
            int rouge = r.nextInt(255);
            int vert = r.nextInt(255);
            int bleu = r.nextInt(255);
            Color c = new Color(rouge, vert, bleu);
            app = new ArcProgressPane(c, i, nbOptions);
            add(app);       
            app.addMouseListener(new MouseListener() {

                @Override
                public void mouseClicked(MouseEvent e) {
                    ArcProgressPane src = (ArcProgressPane) e.getSource();
                    System.out.println("click sur " + src.getPos());
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                }

                @Override
                public void mouseExited(MouseEvent e) {
                }
            });
            
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new javax.swing.OverlayLayout(this));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println("fond");
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
