/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package markingmenu;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Random;

/**
 *
 * @author hakje
 */
public class Pie extends javax.swing.JPanel {

    private int nbOptions;

    /**
     * Creates new form Pie
     */
    public Pie() {
        this(4);
    }

    public Pie(int nbO) {
        initComponents();
        nbOptions = nbO;
        ArcProgressPane app;

        for (int i = 1; i <= nbOptions; i++) {
            Color c = getRandomColor();
            app = new ArcProgressPane(c, i, nbOptions);
            add(app);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        setLayout(new javax.swing.OverlayLayout(this));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private Color getRandomColor() {
        Random r = new Random();
        int rouge = r.nextInt(255);
        int vert = r.nextInt(255);
        int bleu = r.nextInt(255);

        return new Color(rouge, vert, bleu);
    }
}
